### PR TITLE
Add workflow for scraping courses

### PR DESCRIPTION
**Pull request by KevinBatdorf**
This PR adds a mechanism to fetch and parse the course list from https://academy.zerotomastery.io/courses

It checks on a daily schedule but the workflow also has a manual trigger so you could run it on demand as well. If changes are found, it will open a PR. 

> [!TIP]
> ...it will open a PR
>
> It may be more convenient to have it just commit back to `main` but maybe you want to run it a few times to make sure you're confident in it. Then it's only a few updates to the workflow file to change the logic.

### Output

Here's a manual run: https://github.com/KevinBatdorf/ztm-extension/actions/runs/9762033440/job/26944460686
PR it opened: https://github.com/KevinBatdorf/ztm-extension/pull/9
File output: https://github.com/KevinBatdorf/ztm-extension/blob/main/course-details.json
New:
```json
{
  "id": "1806594",
  "name": "Advanced Excel Bootcamp: Data Analytics and Business Intelligence",
  "description": "Master Excel's built-in power tools, including Power Query, Power Pivot Tables, and DAX.",
  "link": "https://zerotomastery.io/courses/business-intelligence-course",
  "author": "Travis Cuzick",
  "thumbnail": "https://process.fs.teachablecdn.com/ADNupMnWyR7kCWRvm76Laz/resize=width:705/https://cdn.filestackcontent.com/Ar6Ma3YcSZuHGE76b2TL"
}
```
Before:
```json
{
  "name": "Advanced Excel Bootcamp: Data Analytics and Business Intelligence",
  "link": "https://zerotomastery.io/courses/business-intelligence-course/"
}
```

### Comments

The IDs appear to be in order from oldest course to newest, so this would also allow for sorting (as mentioned here https://github.com/sithu-khant/ztm-extension/issues/40) along with a custom UI (just overtake the dom and render something new). 

Some other ideas could be to parse the course descriptions, lesson titles, (transcripts??), then create a local embeddings database and make it easy to do some semantic searches for a topic you're interested in (e.g. "What are queues?"). 

### Test

To test it now you need Deno, and you can just run:
```sh
deno run --allow-net --allow-write .github/scripts/scrape-courses.ts
```

Let me know if I missed anything

### CODE REVIEW

**Comment by aneagoie** [comment]
This is a great PR... thank you for putting in the work and writing great detailed information about this PR. Curious to hear what @sithu-khant thinks. Also love the use Deno ;)

Would be a great addition.

**Comment by sithu65** [comment]
@KevinBatdorf the scrapper is scraping the pages those don't exist. 

For example, `ZTM Campus Event Recordings` linked `https://zerotomastery.io/courses/ztm-campus-event-recordings`  don't exist in academy page. It will return a 404 page if you click the course detail icon. There are also for some courses those don't exist in academy page. 

Could you fix that? Don't scrap if there isn't a real course page.

I don't want to show the course detail icon if there isn't a real course description page. That is what the course detail feature does.

**Comment by KevinBatdorf** [comment]
Makes sense. Would you be able to support it if link is set to `null` and it looks like this?

```json
  {
    "id": "2450909",
    "name": "ZTM Campus Event Recordings",
    "description": "Listen to recordings of past Campus events. A great way to keep learning while doing chores or going for a walk!",
    "link": null,
    "author": "Zero To Mastery Instructor Team",
    "thumbnail": "https://process.fs.teachablecdn.com/ADNupMnWyR7kCWRvm76Laz/resize=width:705/https://cdn.filestackcontent.com/yeKu0AUzR6S7BuwqhKcj"
  }
```

**Comment by sithu65** [comment]
Could you just remove the `"link"` key? If you can please remove the whole course list if `link` don't exist. I hope you can skip adding that by `if else` statement.

**Comment by sithu65** [comment]
btw, will this scrapper overwrite the whole file or just add the latest course information at the end? 

What if we want to update that JSON file manually?

**Comment by sithu65** [comment]
I am sorry, I accidentally closed this. Now it is alive again.

**Comment by KevinBatdorf** [comment]
> What if we want to update that JSON file manually?

It will overwrite the whole thing. We could support manual overrides, but then it may result in outdated data if it's not maintained. What do you think? 

> Could you just remove the "link" key? 

We could and it would work the same when consuming it, but is there a reason? It might be less readable if each entry doesn't follow a predictable schema. You might wonder if there was a bug. Let me know and I'm ok changing it though.

> If you can please remove the whole course list if link don't exist. I hope you can skip adding that by if else statement.

Do you think course could remain regardless? For example, this is for the ZTM Campus Event Recordings https://academy.zerotomastery.io/courses/enrolled/2450909 which can be built using the course id

So if search were to be implimented, I'd expect that to show up.

To remove them from details, I think you'd just need to add `.filter((res) => res.link)` to this line (https://github.com/sithu-khant/ztm-extension/blob/main/scripts/ztm-course-details.js#L98) ? I could add that change too.

**Comment by sithu65** [comment]
Actually, this is the check point codes -> https://github.com/sithu-khant/ztm-extension/blob/1be25abcc7dd436988df8770892d5d1c8da5b5a8/scripts/ztm-course-details.js#L121C17-L127C18

But it can easily update to `if (getCourseDetailsAnchor.href !== "null") {` from `if (!getCourseDetailsAnchor.href) {`. Could you update that from your side?

**Comment by KevinBatdorf** [comment]
I noticed quite a few of the links actualy arent pointing to the proper course page. I think it's just outdated on that course listing page.

What I'll do is try to search this course page which has links to the details page. Also has a bit of other useful informaiton too

https://zerotomastery.io/courses/

I'll update that file too to remove entries without links from the details view. 

I'll follow up in a day or so

**Comment by KevinBatdorf** [comment]
I updated this now if you can take a look. I've checked the URLs and they all seem propery linked now too.

There ended up being a few of inconsistencies between the courses depending on where they are listed that made this a bit complicated, but I think I came up with a consistent solution. 

Some courses have different names (e.g. prefixed with "The") and different URL patterns (some use course id, some use a slug), and some have minor grammer inconsistencies (e.g. oxford comma in one title on one page, but not the other 😅)

So here's the flow I landed on.

1. Check the course description page for a _course id_ match
2. Check for an _exact name_ match
3. Split the course name into pieces and just look for a 70% word overlap

Here's the file list if you can check it out now: https://github.com/KevinBatdorf/ztm-extension/blob/18e1ecaa63c08bd602f977a664e1108ef450147e/course-details.json

And the PR the bot opened: https://github.com/KevinBatdorf/ztm-extension/pull/12

I also filtered out the cards with no links in the details script within the extension

Happy to make changes of course so let me know.

**Comment by sithu65** [comment]
@KevinBatdorf did you test the extension with your updated code locally? Is everything okay? The important thing is all the courses must have Course Details icon if they have **real** description links.

**Comment by KevinBatdorf** [comment]
So I tested from this page here: https://academy.zerotomastery.io/courses/

Similar to the video, I clicked on every course link to confirm they went to the corresponnding details page. All good.


https://github.com/sithu-khant/ztm-extension/assets/1478421/6b90c08a-56c7-4f46-9958-72264c7b10b1

Also checked that the courses that shouldn't have a button, don't. All good there too (as far as I can tell)

CleanShot 2024-07-10 at 20 48 35@2x

**Comment by aneagoie** [comment]
This looks great. Great job @KevinBatdorf 👍 

So we are all on the same page: once this is merged, the only thing this adds, is it creates a new PR whenever a new course is added to ZTM /courses page. This PR can then be reviewed for any issues, and then merged with any new course launch. 

Once merged, we can then submit the new extension to the Chrome store. 

If you all give me the 👍 to this comment, @sithu65 feel free to merge this.

**Comment by sithu65** [comment]
Well done, @KevinBatdorf. Thanks for your contributions to the ZTM Extension. I hope you show up again with more brilliant ideas.

I merged it now.

**Comment by KevinBatdorf** [comment]
Sure thing! Have a few fun and maybe useful ideas. As for this PR, the workflow runs once a day at 6am UTC, so in about 5-6 hours from now. Otherwise you can manually trigger it here any time too.

https://github.com/sithu-khant/ztm-extension/actions/workflows/scrape-courses.yml

If any issues come up with the workflow or PR I might not get a notification, but feel free to dm me on discord (kev_xb) or tag me here too

**Comment by sithu65** [comment]
So, this scrapper is going to create a new pull request once a day? So, if we didn't merge those, there will be a ton of pull request?

How about scrapping can happen once a day, but for creating pull request, only if the `course-details.json` got changed?

**Comment by KevinBatdorf** [comment]
No, it's smart enough to only open one at a time, and if there are no changes (you merged it in), then no new PR too

**Comment by sithu65** [comment]
So, it will only open a new PR until we merge the updated one?

**Comment by KevinBatdorf** [comment]
If there's an open PR it won't open a second PR. 

And if the courses list updates again after that PR is open (e.g. you keep it open for a month and new courses are added), the PR will be stale. In that case, the workflow will auto update the PR and _not_ open a new PR.

The PR workflow actually has a breakdown of the logic it uses here: https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#action-behaviour

**Comment by sithu65** [comment]
Cool! that is excellent.

**Comment by KevinBatdorf** [comment]
The run failed for what looks to be a permissions issue from the gh action bot trying to make the PR.

You might need to enable something on the repo to let the bot open PRs. I don't remember doing that but maybe I have a setting elsewhere that it inherits from. 

Can you check out this comment here? https://github.com/peter-evans/create-pull-request/issues/2767#issuecomment-1953810837

**Comment by KevinBatdorf** [comment]
I dug a little deeper on this and the [action](https://github.com/sithu-khant/ztm-extension/actions/workflows/scrape-courses.yml) will fail until until the permissions are set up to allow the action to make the commit.

You should be able to update that here:

https://github.com/sithu-khant/ztm-extension/settings/actions

And it looks like this:

CleanShot 2024-07-15 at 20 56 53@2x

**Comment by sithu-khant** [comment]
Hi there @KevinBatdorf, I did all the steps you suggested. The scrapper is still getting fails.  So, I added you as collaborator. Please accept it and let's see how it goes.

**Comment by KevinBatdorf** [comment]
Looks like setting the permissions explicitly worked!

https://github.com/sithu-khant/ztm-extension/blob/main/.github/workflows/scrape-courses.yml#L10

**Pull request merged**
