### PR TITLE
Fix new html structure in scraper

### PR DESCRIPTION
**Pull request by KevinBatdorf**
This fixes a few changes that were made to the html structure causing the scraper to fail. The id was also removed from the details page, but fuzzy matching the name still works

Here's what the ouput looks like:

https://github.com/KevinBatdorf/ztm-extension/blob/fb9c2c215d6637a59efc3e26ee5dc6cb22521747/course-details.json

### CODE REVIEW

**Comment by sithu-khant** [comment]
Why `Step 1: Join Our Online Classroom`, `Step 2: Choose Your Career Path`, and others have the `link` values? They don't have the detail pages. And I don't want to set the `link` value to the course link (no detail link) if there is no **actual** course detail pages.

Could you set them back to`null` like your previous commit?

P.S please make sure you did check the `name` and `link` keys first rather than other keys in the next time before submitting pull request.

Screenshot 2024-08-08 at 6 51 11 AM

Screenshot 2024-08-08 at 6 43 05 AM

**Comment by KevinBatdorf** [comment]
Technically they have links and separate course links. I'm not sure that's new or not with some recent changes?

https://academy.zerotomastery.io/p/join-the-community

I think it requires a login which the script wouldn't have. 

So we can either include these links or I could have the script check if the page requires a login maybe. What do you think?

**Comment by sithu-khant** [comment]
No, please don't do like that, it will be over engineered, otherwise I won't merge this pull request and your previous pull request is working already.

And you are confused about the `Course Detail` feature. Why do you need to add a course detail icon for `https://academy.zerotomastery.io/p/join-the-community` when you are already in the academy learning page?

And `academy.zerotomastery.io` and `zerotomastery.io` are completely two different places. Your job is to link (course detail icon) the course from `academy.zerotomastery.io` to `zerotomastery.io` page if that course has its own page in `zerotomastery.io`. Not to add the link to course from `academy.zerotomastery.io` to `academy.zerotomastery.io` page.

You don't need to add course detail icon for this course, `https://academy.zerotomastery.io/p/join-the-community`, because you are already on `academy.zerotomastery.io` page, isn't?

**Comment by KevinBatdorf** [comment]
The html structure broke since the ztm team updated the page, so the scraper doesn't work. I'm not sure what you're trying to say about overengineering but when things break we have to fix them.

I can remove the links originating from the paginated courses list. I think those are the ones pointing to the academy site pages. 

I feel you could be a bit friendlier too. The ztm site is really fragmented and inconsistent.

**Comment by sithu-khant** [comment]
I am sorry, I am just trying to explain you what you did previously and what we want. I am sorry if I meant rude to you... and I am not blaming about you. 

+ You should pointed about the code changes on ZTM page. You should say clearly. You just pointed this out `This fixes a few changes that were made to the html structure causing the scraper to fail.` I thought a few changes were yours, not on ZTM page and I am not a member of ZTM team. I didn't know that. And I think it is not about ZTM team changes. The site is backed by Teachable for the learning page.

Again, I am sorry if you misunderstand me.

**Comment by KevinBatdorf** [comment]
It's all good. They made changes to this page that rquire updating the scraper: https://zerotomastery.io/courses/

They removed the course id from the metadata so there's a bit more guessing involved. but I removed any of the academy links now so maybe it's good? here's the output now:

https://github.com/KevinBatdorf/ztm-extension/pull/17/files

**Comment by sithu-khant** [comment]
so, is it working back now? Did you test it properly?

**Comment by KevinBatdorf** [comment]
Yeah I think it's good now. If there's an issue when it runs automatically I'll check it out. 

By the way, the workflow will open a PR but if there are code changes it will open a new PR instead of replacing the old one. The last one from a few weeks ago was never merged so I closed it now. When this runs again it should open a new one.

**Pull request merged**
